### ISSUE TITLE
Leetcode 用的是 python 3,7，TreeNode 是预定义的

### ISSUE THREAD

**Issue by SleepyBag** [Hongze-Wang/LeetCode_Python#1]
我没明白为什么说下面这种函数定义只有 leetcode 才能用：
def isMirror(self, left: TreeNode, right: TreeNode) -> bool
但是我猜想是你用的 python 3.6 以下的版本，或者没有定义 TreeNode，不然的话在任何一个 python 解释器上这样的函数定义应该都是合法的

**Comment by Hongze-Wang** [comment]
这个问题我在微信上问过你，你当时没理解我的意思。这种定义函数的方式(指以":"指定 参数类型)，"->"指示返回值，只能在LeetCode上使用，Anaconda和PyCharm都不支持这种语法。

**Comment by Hongze-Wang** [comment]
> 我没明白为什么说下面这种函数定义只有 leetcode 才能用：
> def isMirror(self, left: TreeNode, right: TreeNode) -> bool
> 但是我猜想是你用的 python 3.6 以下的版本，或者没有定义 TreeNode，不然的话在任何一个 python 解释器上这样的函数定义应该都是合法的

PyCharm也支持这种语法，但一般的解释器是不支持的。

**Comment by Hongze-Wang** [comment]
> 我没明白为什么说下面这种函数定义只有 leetcode 才能用：
> def isMirror(self, left: TreeNode, right: TreeNode) -> bool
> 但是我猜想是你用的 python 3.6 以下的版本，或者没有定义 TreeNode，不然的话在任何一个 python 解释器上这样的函数定义应该都是合法的

多谢指教。
